name: Actualizar Opiniones de Google

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Consultar API de Apify y guardar JSON
        run: |
          curl -L "https://apify.com{{ secrets.APIFY_TOKEN }}&format=json" -o opiniones.json

      - name: Subir cambios al repositorio de GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@://github.com'
          git add opiniones.json
          git commit -m "Automatización: Actualización de opiniones de Google" || exit 0
          git push
