name: Actualizar Opiniones de Google

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta una vez al día automáticamente
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  update-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Descargar Dataset de Apify
        run: |
          # Descargamos el JSON usando la URL oficial de la API de Apify de forma segura
          curl -L "https://apify.com{{ secrets.APIFY_TOKEN }}&format=json" > opiniones.json

      - name: Hacer Commit y Push del archivo JSON
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@://github.com'
          git add opiniones.json
          git commit -m "Automatización: Actualización de opiniones de Google" || exit 0
          git push
